<!-- 
/**
 * Copyright Notice for Software Code (Cognizant Proprietary/owned)
 *
 * Â© Cognizant Technology Solutions 2015
 * All rights reserved.
 *
 * Except for open source or proprietary third party software components embedded in this Cognizant proprietary software program ("Program"),
 * this Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights and statutes in India,
 * the United States and other countries. Except as expressly permitted by Cognizant and its third party licensors, the Program may neither be used, reproduced,
 * transmitted, distributed or modified, either in whole nor in part, in any manner or form whatsoever (including without limitation electronic,
 * mechanical, printing, photocopying, recording or otherwise), without the prior, express, written consent and acknowledgment of Cognizant Technology Solutions.
 * Any violation may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law
 */ 
-->

<?php $_product = $this->getProduct(); ?>

<script src="http://54.225.201.242/v1/bazaAR.js?token=<?php echo Mage::getStoreConfig('api/general/api_key',Mage::app()->getStore()); ?>"></script>

<video id="videoElement" controls="false" height="480" width="640" autoplay="true" hidden></video>
<div id="videoContainer" style="display: none;">
    <canvas id="canvasElement" height="480" width="640"></canvas>

    <div id="canvasContainer">
        <aside id="canvasSidebarHeader">
            <ul id="canvasControls">
                <li><input type="button" id="canvasScreenClose" value="" ></li>
                <li><input type="button" id="canvasScreenShot" value="" ></li>
                <li><input type="button" id="canvasScreenClear" value="" ></li>                
            </ul>
        </aside>
        <aside id="canvasSidebar"></aside>
    </div>
</div>

<?php $augmentedValue = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('augmented'); ?>

<?php if (!($augmentedValue == "None" || $augmentedValue == "")) : ?>

    <a href="#" class="tryProduct" onclick='return showVideoContainer("<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>", "<?php echo $augmentedValue ?>")'>
        Try Now
    </a><br/><br/>

<?php endif; ?>

<script type="text/javascript">
    function getBaseJsUrl() { return '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>'; } 
</script>